version: '3.8'

services:
  app:
    build:
      dockerfile:  ./Dockerfile
      context: .
    container_name: streamlit-roof-annotation
    ports:
        - 8082:8082
    volumes:
      - ./src:/src
